version: '3'
services:
  person-api:
    image: person-api:latest
    build:
      context: ./PersonAPI
      dockerfile: ./Dockerfile
    ports:
      - "8010:8010"
    networks:
      - person-network

    depends_on: 
      - baseperson

  baseperson:
      image: mongo:latest
      ports:
        - 57017:27017

      networks: 
        - person-network

networks:
  person-network:
    driver: bridge


      
      